---
# tasks file for mysql
- name: install dependencies
  apt:
    name=python-mysqldb
    state=present
    update_cache=yes

- name: install mysql-server
  apt:
    name=mysql-server
    state=present
    update_cache=yes

- name: mysql is running
  service:
    name=mysql
    state=started
    enabled=yes
  tags:
  - no-docker

- name: ensure mysql listen on all ports
  lineinfile:
    dest=/etc/mysql/my.cnf
    regexp=^bind-address
    line="bind-address = 0.0.0.0"
  notify: restart mysql

- name: create demo database
  mysql_db: name={{ db_name }} state=present
  tags:
  - no-docker

- name: create demo user
  mysql_user:
    name={{ db_user }}
    password={{ db_password }}
    priv={{ db_name }}.*:ALL host='%'
    state=present
  tags:
  - no-docker