---
- hosts: loadbalancer
  become: true
  tasks:

    - name: install nginx
      apt:
        name=nginx
        state=present
        update_cache=yes

    - name: ensure nginx is started
      service:
        name=nginx
        state=started
        enabled=yes

  handlers:
    - name: restart nginx
      service: name=nginx state=restarted