---
- hosts: all
  become: true
  pre_tasks:
    - name: update apt cache
      apt: update_cache=yes

  tasks:
    - name: install packages
      apt: name={{ item }} state=latest
      with_items:
        - lynx
        - vim
        - mc
        - joe

  post_tasks:
    - name: hostname
      command: hostname

- include: webserver.yml