---
- hosts: all
  become: true
  tasks:

    - name: install apache2 and server components
      apt: name={{ item }} update_cache=yes
      with_items:
        - apache2
        - libapache2-mod-wsgi
        - python-pip
        - python-virtualenv

    - name: apache2 is running
      service: name=apache2 state=started enabled=yes

    - name: check mod rewrite
      apache2_module:
        state=present
        name=rewrite
      notify:
        - restart apache2

  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted